backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)

# Publish mode
publish_mode: editorial_workflow

# Media and Public folders
media_folder: "public/blog/images"
public_folder: "/blog/images"

# Collections
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Read Time", name: "readTime", widget: "string", hint: "e.g., 5 min read" }
      - { label: "Author", name: "author", widget: "string", default: "Herman Hylland" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          allow_add: true,
          hint: "Add tags for the post (e.g., React, AI, Design)"
        }
      - { label: "Body", name: "body", widget: "markdown" }
